name: "VNC Web Browser"
version: "0.12.1"
slug: "vnc_web_browser"
description: "Display multiple web pages through VNC"
url: "https://github.com/freezem76/ha-vnc-web-browser"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
ports:
  5901/tcp: 5901
  5902/tcp: 5902
  5903/tcp: 5903
  5904/tcp: 5904
ports_description:
  5901/tcp: "VNC port for display 1"
  5902/tcp: "VNC port for display 2"
  5903/tcp: "VNC port for display 3"
  5904/tcp: "VNC port for display 4"
schema:
  displays:
    - url: str?
      resolution: match(^\d+x\d+$)
      port: int(5901,5904)
      depth: int(8,32)?
      view_only: bool?
      browser_args: str?
  vnc_password: password?
options:
  displays:
    - url: "http://homeassistant.local:8123"
      resolution: "1280x720"
      port: 5901
      depth: 16
      view_only: false
      browser_args: ""
  vnc_password: ""